const MAX_AGE=28800;
const j=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json;charset=utf-8'}});
async function hmac(v,secret){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const b=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(v));return btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function session(env){const p=btoa(JSON.stringify({u:env.ADMIN_USER,e:Date.now()+MAX_AGE*1000}));return p+'.'+await hmac(p,env.SESSION_SECRET)}
async function guard(req,env){const m=(req.headers.get('Cookie')||'').match(/(?:^|;\s*)nexa_session=([^;]+)/);if(!m)return j({erro:'Faça login para continuar.'},401);const [p,s]=m[1].split('.');if(!p||s!==await hmac(p,env.SESSION_SECRET))return j({erro:'Sessão inválida.'},401);try{if(JSON.parse(atob(p)).e<Date.now())throw 0}catch{return j({erro:'Sessão expirada.'},401)}return null}
function cookie(v,age=MAX_AGE){return 'nexa_session='+v+'; Max-Age='+age+'; Path=/; HttpOnly; Secure; SameSite=Lax'}
export default {async fetch(req,env){
 const u=new URL(req.url),p=u.pathname;
 if(p==='/login'&&req.method==='GET')return env.ASSETS.fetch(new Request(new URL('/login.html',u)));
 if(p==='/login'&&req.method==='POST'){const b=await req.formData(),user=String(b.get('usuario')||''),pass=String(b.get('senha')||'');if(user!==env.ADMIN_USER||pass!==env.ADMIN_PASSWORD){const r=await env.ASSETS.fetch(new Request(new URL('/login.html',u)));let t=await r.text();t=t.replace('<form method="post" action="/login">','<form method="post" action="/login"><p class="message" role="alert">Usuário ou senha inválidos.</p>');return new Response(t,{status:401,headers:{'content-type':'text/html;charset=utf-8'}})}return new Response(null,{status:302,headers:{Location:'/', 'Set-Cookie':cookie(await session(env))}})}
 if(p==='/logout'&&req.method==='POST')return new Response(null,{status:302,headers:{Location:'/login','Set-Cookie':cookie('',0)}});
 if(p==='/api/energia/leitura'&&req.method==='POST'){try{const b=await req.json(),x={dispositivo:String(b.dispositivo||'ESP32').slice(0,80),energia_kwh:+Number(b.energia_kwh).toFixed(4),custo_brl:+Number(b.custo_brl||0).toFixed(2),potencia_w:+Number(b.potencia_w||0).toFixed(2),tensao_v:+Number(b.tensao_v||0).toFixed(2),corrente_a:+Number(b.corrente_a||0).toFixed(3),timestamp:b.timestamp||new Date().toISOString()};if(!Number.isFinite(x.energia_kwh)||x.energia_kwh<0||x.custo_brl<0)throw 0;await env.DB.prepare('INSERT INTO energy_readings(dispositivo,energia_kwh,custo_brl,potencia_w,tensao_v,corrente_a,timestamp) VALUES(?,?,?,?,?,?,?)').bind(x.dispositivo,x.energia_kwh,x.custo_brl,x.potencia_w,x.tensao_v,x.corrente_a,x.timestamp).run();return j({mensagem:'Leitura recebida.',leitura:x},201)}catch{return j({erro:'Envie energia_kwh e valores numéricos válidos.'},400)}}
 const denied=await guard(req,env);if(denied&&p!=='/login')return denied;
 if(p==='/'&&req.method==='GET')return env.ASSETS.fetch(new Request(new URL('/index.html',u)));
 if(p==='/api/energia'&&req.method==='GET'){const r=await env.DB.prepare('SELECT dispositivo,energia_kwh,custo_brl,potencia_w,tensao_v,corrente_a,timestamp FROM energy_readings ORDER BY id DESC LIMIT 500').all(),rows=r.results||[],pd={};for(const x of rows){pd[x.dispositivo]??={energia_kwh:0,custo_brl:0,leituras:0};pd[x.dispositivo].energia_kwh+=x.energia_kwh;pd[x.dispositivo].custo_brl+=x.custo_brl;pd[x.dispositivo].leituras++}return j({leituras:rows,resumo:{energia_kwh:+rows.reduce((a,x)=>a+x.energia_kwh,0).toFixed(3),custo_brl:+rows.reduce((a,x)=>a+x.custo_brl,0).toFixed(2),dispositivos:Object.keys(pd).length,leituras:rows.length},por_dispositivo:Object.entries(pd).map(([dispositivo,x])=>({dispositivo,energia_kwh:+x.energia_kwh.toFixed(3),custo_brl:+x.custo_brl.toFixed(2),leituras:x.leituras}))})}
 if(p==='/api/store'&&req.method==='POST'){const b=await req.json();if(!b.name||!Array.isArray(b.sheets))return j({erro:'Dados inválidos.'},400);const d=await env.DB.prepare('INSERT INTO datasets(name) VALUES(?)').bind(b.name).run(),id=d.meta.last_row_id;for(const s of b.sheets){const sh=await env.DB.prepare('INSERT INTO dataset_sheets(dataset_id,sheet_name,columns_json) VALUES(?,?,?)').bind(id,s.name,JSON.stringify(s.columns||[])).run(),sid=sh.meta.last_row_id;for(let i=0;i<s.rows.length;i+=50){await env.DB.batch(s.rows.slice(i,i+50).map(r=>env.DB.prepare('INSERT INTO rows_data(sheet_id,row_json) VALUES(?,?)').bind(sid,JSON.stringify(r))))}}return j({ok:true,id},201)}
 if(p==='/api/datasets'&&req.method==='GET')return j((await env.DB.prepare('SELECT id,name,created_at FROM datasets ORDER BY id DESC').all()).results);
 if(p==='/api/datasets'&&req.method==='DELETE'){await env.DB.prepare('DELETE FROM datasets').run();return j({ok:true})}
 if(p==='/api/me')return j({ok:true});
 return env.ASSETS.fetch(req);
}};